### ISSUE TITLE
it doesnt work on steamvr beta 2.2.2

### ISSUE THREAD

**Issue by ghost** [RileyGuy/Impressive#1]

**Comment by BlueCyro** [comment]
If you could, please start your game, wait for it to load, make sure the Steam Link OSC settings are correct, and then close it. Afterwards, send me the latest log.

**Comment by BlueCyro** [comment]
Also be sure you're opted into the beta on the meta quest store as well so that the steam link versions match.

**Comment by ghost** [comment]
still not working with or without betas on

**Comment by BlueCyro** [comment]
Make absolutely sure that the SteamLink on your meta quest (that is, the app on the meta quest store) is opted into the beta as well. I've added tongue support (just simple in & out), but this mod would have worked regardless of that. Make sure **both** SteamVR on your computer is set to the beta branch **and** the meta quest app. Also make sure the OSC port is set correctly in SteamVR and that both the eye and face tracking options are enabled as well.
