### ISSUE TITLE
Disabling Mod via Mod Settings Does Not Restore SRanipal Tracking

### ISSUE THREAD

**Issue by FlameSoulis** [RileyGuy/Impressive#4]
If you switch headsets frequently and disable the mod via Mod Settings, the face tracking from SRanipal does not become active.

**Comment by BlueCyro** [comment]
I'll have to look at this at some point, but I wanna say that this mod registers a new mouth & eye data source alongside the SR one, so I'm not sure if registering the same type of device twice overrides the previous implementation. Depending on how tricky it is to make work this may just be something we've gotta deal with. SRAnipal generally doesn't like playing nice.

**Comment by ProbablePrime** [comment]
Ran into this because I was back in index after trying the quest pro. 

I think I can make a change here on our end to fix this.

Will have to check with Froox, but i'm gonna add this to Next Week.

**Comment by ProbablePrime** [comment]
The update(2024.1.29.1304), should have resolved this. You can find the update notes here: https://discord.com/channels/1040316820650991766/1154514012143362151/1201646129884958731

> Devices providing mouth tracking data are now ignored as source of mouth tracking data when they indicate that they do not currently track (implemented by @ProbablePrime)

Here's the change:
![image](https://github.com/RileyGuy/Impressive/assets/8791132/05dca6c6-4572-4c8f-893c-a64b485a643e)

Basically provided your input driver is setting IsTracking to false when the mod is disabled or steam OSC is unavailable, it should swap back to SRanipal.

Eyes already had a similar line to the above, so should have been fine.

Let me know!

@RileyGuy @FlameSoulis

**Comment by FlameSoulis** [comment]
I'll give it a test later on after work. If all is good, then I'll mark the case as closed. Otherwise, I recall there was a ticket on the Resonite Github regarding adding OSC functions strictly for face tracking by Geenz.

**Comment by ProbablePrime** [comment]
Oh of course, native OSC integration into Resonite would be a separate issue, this just makes the mod less annoying to leave on :D

**Comment by BlueCyro** [comment]
Closing as no longer needed since Resonite supports Quest Pro facetracking natively now.
