### ISSUE TITLE
Eye tracking inaccurate compared to the calibration software on headset, or vrcfacetracking.

### ISSUE THREAD

**Issue by ModernBalloonie** [RileyGuy/Impressive#6]
This is after a full calibration, and originally I thought this was just a quest pro issue, but it might actually be a problem with the mod.

For instance, Vrcfacetracking for VRC is basically fine, but there's something with the impressive mod that makes the eye tracking a bit inaccurate. Sadly I can't really demonstrate this properly, but something is off.

To reiterate, this is after a calibration, and it's pretty much almost perfect in the calibration software, and in VRC. Just in Resonite somethings off.

Update: on further testing it seems like it's an offset, like the further i am from the center of the screen, the more offset it is.

**Comment by BlueCyro** [comment]
What is your testing process for this? Make sure you use the AvatarRawEyeData component and not just values from the eye manager when you're measuring the accuracy in Resonite.

**Comment by ModernBalloonie** [comment]
> What is your testing process for this? Make sure you use the AvatarRawEyeData component and not just values from the eye manager when you're measuring the accuracy in Resonite.

I'm using the new eye tracking tester in Resonite Essentials - Examples which uses the eye tracking data from avatarraweyedata.

https://github.com/RileyGuy/Impressive/assets/82356528/46d34d0a-2aad-4313-8861-f98245ca51b2

In this video I'm trying to look at the specular dot on the sphere, but it ends up going past the sphere. When i move my head up and down, this worsens a bit, like there's an offset.

**Comment by BlueCyro** [comment]
Closing as no longer needed since Resonite supports Quest Pro facetracking natively now.
